apiVersion: v1                              
kind: Namespace                             
metadata:                                                    
  name: typicode-express
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: typicode-express-app
  namespace: typicode-express
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: typicode-express-dep
  template:
    metadata:
      labels:
        app: typicode-express-dep
    spec:
      containers:
        - name: typicode-express-pod
          image: swagatachaudhuri/typicode-express:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 25m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 8080
              name: "port"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: "port"
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3  
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: "port"
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3                        
      terminationGracePeriodSeconds: 0              
---
apiVersion: v1
kind: Service
metadata:
  name: typicode-express-svc
  namespace: typicode-express
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: typicode-express-dep                  